zzang-coding-test/conding-test

- jeongs/jan/23-01-18-크기가작은부분문자열.js
문제 설명
숫자로 이루어진 문자열 t와 p가 주어질 때, t에서 p와 길이가 같은 부분문자열 중에서, 이 부분문자열이 나타내는 수가 p가 나타내는 수보다 작거나 같은 것이 나오는 횟수를 return하는 함수 solution을 완성하세요.
예를 들어, t="3141592"이고 p="271" 인 경우, t의 길이가 3인 부분 문자열은 314, 141, 415, 159, 592입니다. 이 문자열이 나타내는 수 중 271보다 작거나 같은 수는 141, 159 2개 입니다.
8분.
> [2023-01-18] 크기가 작은 부분 문자열 (1단계)

- ezz/jan/2023-01-18-두 수의 차.java
정수 num1과 num2가 주어질 때, num1에서 num2를 뺀 값을 return하도록 soltuion 함수를 완성해주세요.
1분
https://school.programmers.co.kr/learn/courses/30/lessons/120803
> 프로그래머스-두 수의 차2

- jeongs/jan/23-01-19-가장가까운같은글자.js
<h6 class="guide-section-title" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; -webkit-font-smoothing: antialiased; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); …
> [23-01-19] 가장 가까운 글자 (1단계)

- ezz/jan/2023-01-19-짝수의 합.java
정수 n이 주어질 때, n이하의 짝수를 모두 더한 값을 return 하도록 solution 함수를 작성해주세요.
10 m Down
[](https://school.programmers.co.kr/learn/courses/30/lessons/120831)
> the sum of even numbers

- jeongs/jan/23-01-19-귤-고르기.js
<h6 class="guide-section-title" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; -webkit-font-smoothing: antialiased; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); …
> [23-01-20] 귤 고르기 (2단계)

- ezz/jan/2023-01-20-각도기.java
각에서 0도 초과 90도 미만은 예각, 90도는 직각, 90도 초과 180도 미만은 둔각 180도는 평각으로 분류합니다. 각 angle이 매개변수로 주어질 때 예각일 때 1, 직각일 때 2, 둔각일 때 3, 평각일 때 4를 return하도록 solution 함수를 완성해주세요.
20분이하
if(else if문을 사용 시){
}else {
if(앞 선 조건을 제외하세요.){
}else {
}15분을 버린다. 나와 같이
[](https://school.programmers.co.kr/learn/courses/30/lessons/120829)
> 나는 반환한다. 각도에 따른 다른 값을.

- ezz/jan/2023-01-21-배열의 평균값.java
30분 이상
나는 믿어야 합니다. 내 자신을. 그리고 경계해야 합니다. 오탈자를. 
[](https://school.programmers.co.kr/learn/courses/30/lessons/120817#)
> 나는 구합니다. 정수 배열의 평균값을.

- soba/jan/2022-01-21-짝수의합구하기문제.java
> 이것은 짝수의 합 구하기 문제

- ezz/jan/2023-01-22-피자 나눠 먹기(1).java
머쓱이네 피자가게는 피자를 일곱 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 주어질 때, 모든 사람이 피자를 한 조각 이상 먹기 위해 필요한 피자의 수를 return 하는 solution 함수를 완성해보세요.
10분이내
EZ
[](https://school.programmers.co.kr/learn/courses/30/lessons/120814)
> 나는 먹어봤다. 4조각의 피자조각을.

- jeongs/jan/23-01-22-명예의 전당.js
> [23-01-22] 명예의 전당 (1단계)

- soba/jan/2022-01-22-두수의나눗셈문제.java
두 수의 나눗셈 문제
10분
캐스팅(형변환)의 중요성을 간과하고 있었다 캐스팅은 굉장히 중요해. 잊지마
> 이것은 두 수의 나눗셈 문제!

- soba/jan/2022-01-22-양꼬치문제.java
양꼬치 10개를 시키면 음료수 하나를 써비스로 주는 문제
30분
여러방법을 시도하다 캐스팅(형변환)을 이용하는 것이 가장 효율적인 방식임을 발견..
캐스팅은 굉장히 중요하고 쉬우면서 유용하다
> 이것은 양꼬치와 음료수 서비스 문제!

- jeongs/jan/23-01-23-기사단원의무기.js
> [23-01-23] 기사단원의 무기 (1단계)

- soba/jan/2022-01-23-각도기&피자나눠먹기문제.java
각도기 문제 , 피자나눠먹기1 문제
도합 10분
1. if else if 와 친숙
2. 올림을 어떻게 처리할것인가
> 이것은 각도기와 피자 나눠먹기 문제 !!

- jeongs/jan/23-01-24-숫자카드나누기.js
> [23-01-24] 숫자 카드 나누기 (2단계)

- soba/jan/2022-01-24-배열원소길이문제.java
배열원소길이문제
15분
length 랑 length(); 가 각각 기능이 다름;
length 는 배열의 길이를 구하는 거고
length(); 문자열의 길이를 구하는 것
이 차이를 몰라서 좀 헤맸음
> 이것은 배열원소길이문제!

- jeongs/jan/23-01-25-삼총사.js
> [23-01-25] 삼총사 (1단계)

- soba/jan/2022-01-25-배열뒤집기문제.java
> 2022 01 25 배열뒤집기문제

- jeongs/jan/23-01-26-귤고르기-재풀이.js
<div class="guide-section " id="tour2" style="box-sizing: border-box; padding: 1rem; margin: 0px; color: rgb(38, 55, 71); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; overflow-y: auto; background-color: rgb(38, 55, 71); width: calc(40% - 12px); letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; …
> [23-01-26] 귤 고르기 재풀이 

- soba/jan/2022-01-26-삼각형의완성조건1.java
삼각형의 완성조건 문제
10분
Arrays클래스의 sort() 메서드를 이용하면 배열을 정렬할 수 있다.
삼항연산자
조건문 ? 참 : 거짓을 사용하면 코드를 더욱 간결하게 표현할 수 있다.
> 이것은 삼각형의 완성조건 문제!

- jeongs/jan/23-01-27-과일장수.js
> [23-01-27] 과일장수 (1단계)

- soba/jan/2022-01-27-짝수는싫어요.java
짝수는 싫어요 문제
15분
n 이하의 홀수만을 추출하여 배열로 만든다고 할 때 발생하는 규칙성을 발견하는 것이 핵심
> 이것은 짝수는 싫어요 문제!

- soba/jan/2022-01-28-중복된숫자개수와피자나눠먹기3.java
중복된 숫자 개수 구하기와 피자나눠먹기 3
1. 5분 
2. 10분 내
> 이것은 중복된숫자개수와피자나눠먹기3

- jeongs/jan/23-01-28-할인행사.js
> [23-01-28] 할인행사 (2단계)

- jeongs/jan/23-01-29-햄버거만들기.js
> [23-01-29] 햄버거 만들기 (1단계)

- soba/jan/2022-01-29-머쓱이보다키큰사람문제.java
이것은 머쓱이보다 키 큰 사람 문제 !!
5분컷
1차로 그냥 풀어보고 , 삼항연산자로도 풀어봤당
> 이것은 머쓱이보다 키 큰 사람 문제 !!

- ezz/jan/2023-01-29-배열뒤집기.java
문제 설명
정수가 들어 있는 배열 num_list가 매개변수로 주어집니다. num_list의 원소의 순서를 거꾸로 뒤집은 배열을 return하도록 solution 함수를 완성해주세요.
##제한사항
1 ≤ num_list의 길이 ≤ 1,000
0 ≤ num_list의 원소 ≤ 1,000
10분 이내
https://school.programmers.co.kr/learn/courses/30/lessons/120821
> 나.성공한다.배열뒤집기.

- jeongs/jan/23-01-30-콜라문제.js
> [23-01-30] 콜라문제 (1단계)

- soba/jan/2022-01-30-문자열에서특정문자제거.java
문자열에서 특정문자 제거하기
5분
string 클래스의 replace메서드를 이용하자 replace(oldchar, newchar)
> 이것은 문자열에서 특정문자 제거하기 문제 !!

- ezz/jan/2023-01-30-문자열뒤집기.java
문제 설명
문자열 my_string이 매개변수로 주어집니다. my_string을 거꾸로 뒤집은 문자열을 return하도록 solution 함수를 완성해주세요.
20분 이상
substring 를 이용하면 문자열을 잘라서 붙일 수 있다!
[](https://school.programmers.co.kr/learn/courses/30/lessons/120822)
https://yongku.tistory.com/entry/%ED%94%84%EB%A1%9C%EA%B7%B8%EB%9E%98%EB%A8%B8%EC%8A%A4-%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%92%A4%EC%A7%91%EA%B8%B0-%EC%9E%90%EB%B0%94JAVA
> 프로그래머스-문자열뒤집기.java

- jeongs/jan/23-01-31-푸드파이터대회.js
> [23-01-31] 푸드 파이터 대회 (1단계)

- ezz/jan/2023-01-31-배열원소의길이.java
문제 설명
문자열 배열 strlist가 매개변수로 주어집니다. strlist 각 원소의 길이를 담은 배열을 retrun하도록 solution 함수를 완성해주세요.
##제한사항
1 ≤ strlist 원소의 길이 ≤ 100
strlist는 알파벳 소문자, 대문자, 특수문자로 구성되어 있습니다.
##입출력 예
["We", "are", "the", "world!"]의 각 원소의 길이인 [2, 3, 3, 6]을 return합니다.
["I", "Love", "Programmers."]의 각 원소의 길이인 [1, 4, 12]을 return합니다.
20분 이내
반복문 조건에서는 length뒤에 ()를 붙이지 않는다. 
(https://school.programmers.co.kr/learn/courses/30/lessons/120854)
> 나. 구한다. 문자열배열의길이

- soba/jan/2023-01-31-배열자르기문제.java
배열자르기 문제
10분
Arrays.copyOfRange() 를 이용해주면 굉장히 편리하다
> 이것은 배열자르기 문제 !!

- soba/feb/2023-02-01-개미군단.java
> 개미군단 문제 feb파일에 다시 넣어서 올립니다

- soba/feb/2023-02-02-제곱수판별하기문제.java
20분
Math.sqrt() 를 이용하면 제곱근을 구할 수 있는데 실수형으로 출력된다 ex) 5.0
그런데 5와 5.0이 같은 지 비교해보면 같다고 처리가 되더라 (나는 자바가 이 둘을 다르게 인식하는 줄 알았음...)
그래서 그걸 깨닫고 나니 굉장히 간단하게 문제가 풀렸다.
또 최대한 간결하게 코드를 짜보려고 노력했다.
그랬더니 한줄 컷이 가능했다.
> 이것은 제곱수 판별하기 문제 !!

- jeongs/feb/23-02-02-둘만의암호.js
- jeongs/feb/23-02-03-둘만의암호-solved.js
> [23-02-02 ~ 23-02-03] 둘만의 암호 (7ㅐ같이 승리. 1단계 맞냐?) 

- soba/feb/2023-02-03-세균증식.java
10분~15분
쉬프트 연산자에 대한 점을 배웠다
쉬프트 연산자는 피연산자를 2진수로 표현하였을 때 수를 << , >> 방향 대로 각각 1씩 이동시키는 역할을 한다
중요한 건 이것이 뭘 의미하느냐, 비트들이 왼쪽으로 한칸씩 이동하면 2만큼 곱해주는 효과를 가진다
따라서 5 << 1 이면 10으로 바뀌고 5 << 2 면 20으로 바뀐다.
반대로 20 >> 1 이면 10, 20 >> 2 이면 다시 5로 돌아온다.
그렇기에 쉬프트 연산자는 2의 거듭제곱수를 곱셈해주거나 나눗셈해주는 기능을 가진다
> 이것은 세균증식 문제 !!

- jeongs/feb/23-02-05-행렬의덧셈.js
> [23-02-05] 행렬의 덧셈 [1단계]

- ezz/feb/2024-02-05-분수의덧셈.java
문제 설명
첫 번째 분수의 분자와 분모를 뜻하는 numer1, denom1, 두 번째 분수의 분자와 분모를 뜻하는 numer2, denom2가 매개변수로 주어집니다. 두 분수를 더한 값을 기약 분수로 나타냈을 때 분자와 분모를 순서대로 담은 배열을 return 하도록 solution 함수를 완성해보세요.
##제한 사항
0 <numer1, denom1, numer2, denom2 < 1,000
1시간 이상 
반복문안에 조건문을 쓰는게 아직 부족한 것 같다. 연습이 필요하다.
이거 때문에 시간을 엄청 잡아먹고 기약분수를 구하는 방법을 구글링했다.
💡 분수의 덧셈은
1. answer에 담아 리턴할 분자 변수, 분모 변수 선언
2. 유클리드 호제법을 통해 최대공약수를 구하여 return 될 분자 분모의 의 값을 알아낼 수 있다.
3. 구한 값들을 answer에 담아 리턴 
하는 방법으로 구할 수 있었는데 유클리드 호제법은 간단히 말해 최대공약수를 구할 때 서로를 나누어 원하는 수를 얻는 방법이다.
https://school.programmers.co.kr/learn/courses/30/lessons/120808
https://skulter.tistory.com/21
> 어렵다. 기약분수.최대공약수.

- soba/feb/2023-02-05-과일장수.java
30분이상
정렬해서 규칙성을 파악하니까 굳이 각각 배열을 만들어서 풀 필요는 없었다..
score[배열의크기 - m] 의 숫자를 뽑아 * m 을 해주고
인덱스가 음수가 되면 멈추고 에러를 막아주는 기능도 추가해줘야 했다..
> 이것은 과일장수 문제 !!

- ezz/feb/2023-02-06-배열두배만들기.java
정수 배열 numbers가 매개변수로 주어집니다. numbers의 각 원소에 두배한 원소를 가진 배열을 return하도록 solution 함수를 완성해주세요.
##제한 사항
-10,000 ≤ numbers의 원소 ≤ 10,000
1 ≤ numbers의 길이 ≤ 1,000
10분 이내
https://school.programmers.co.kr/learn/courses/30/lessons/120809
> 두배만든다. 정수 배열을

- jeongs/feb/23-02-06-실패율.js
<h2 style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0.25rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 26px; line-height: 1.4; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.009em; -webkit-font-smoothing: antialiased; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); text-decoration-thickness: …
> [23-02-06] 실패율 (1단계)

- soba/feb/2023-02-06-행렬의덧셈2차원.java
20분 이상
2차원 배열에 대하여 익숙하지 않아 어떻게 하는지 몰랐다 ㅠ 그래서 처음에 파악하는데 시간이 많이 걸렸다
2차원 구조 즉 행렬의 구조에 대해 알게 되면 그 이후부터는 굉장히 쉽게 풀 수 있는 문제이다
> 이것은 행렬(2차원배열)의 덧셈 문제 !!

- soba/feb/공던지기.java
1시간
자꾸 테스트 20, 22 에서 막힘..  낼 다시 공부해봐야갯숨
+) 아 결국 numbers.length를 넘어가면 0으로 초기화 되는것이 마치 % 로 나머지를 구해주는 메커니즘과 동일하구나
그래서 % 를 써서 풀라는 것이구나 이해 완료
> 이것은 공던지기 문제 !!

- ezz/feb/2023-02-07-피자나눠먹기.java
머쓱이네 피자가게는 피자를 여섯 조각으로 잘라 줍니다. 피자를 나눠먹을 사람의 수 n이 매개변수로 주어질 때, n명이 주문한 피자를 남기지 않고 모두 같은 수의 피자 조각을 먹어야 한다면 최소 몇 판을 시켜야 하는지를 return 하도록 solution 함수를 완성해보세요.
20분 이내 
gcd 알고리즘을 통해 코드를 더 간단하게 줄일 수 있었다.
(https://school.programmers.co.kr/learn/courses/30/lessons/120815)
> 피자를 나눠 먹다. 공평한. 같은 수의 조각으로.

- ezz/feb/2023-02-08-짝수가싫어요.java
문제 설명
정수 n이 매개변수로 주어질 때, n 이하의 홀수가 오름차순으로 담긴 배열을 return하도록 solution 함수를 완성해주세요.
제한사항
1 ≤ n ≤ 100
1시간이상 
풀리지 않을 땐 새로운 방법이 있는지 고민해보자.
오름차순으로 정렬하라고 해서  arrays.sort() 만 있는 건 아니다.
[](https://school.programmers.co.kr/learn/courses/30/lessons/120813)
> 나는 싫어한다. 짝수라는 녀석을.

- jeongs/feb/23-02-07-오픈채팅방.js
<h2 style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0.25rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 26px; line-height: 1.4; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.009em; -webkit-font-smoothing: antialiased; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); text-decoration-thickness: …
> [23-02-07] 오픈채팅방 [2단계]

- jeongs/feb/23-02-09-숫자짝꿍.js
> [23-02-09] 숫자짝꿍 [1단계 치고어려웠]

- soba/feb/2023-02-08-편지와옷가게할인받기.java
> 이것은 편지와 옷가게할인 문제 !!

- ezz/feb/2023-02-10-직각삼각형만들기.java
문제 설명
"*"의 높이와 너비를 1이라고 했을 때, "*"을 이용해 직각 이등변 삼각형을 그리려고합니다. 정수 n 이 주어지면 높이와 너비가 n 인 직각 이등변 삼각형을 출력하도록 코드를 작성해보세요.
제한 사항
1 ≤ n ≤ 10
10분 이내 
별 찍기 오랜만 쏘 ez~~~
https://school.programmers.co.kr/learn/courses/30/lessons/120823
> 샤이닝 스털~ 밤 하늘의 퍼얼~

- jeongs/feb/23-02-10-신고결과받기.js
<p style="box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: rgb(178, 192, 204); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.1px; overflow-wrap: break-word; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); text-decoration-thickness: …
> [23-02-10] 신고결과받기 [1단계]

- soba/feb/2023-02-10-암호해독.java
20분
1. 배수를 활용 ex) 3*1 3*2 3*3 ..
2. .length()를 활용, -1 해줘야함
3. for문사용
> 2023-02-10-암호해독 문제입니다

- jeongs/feb/23-02-11-중복순열연습.js
1 ~ n까지 번호가 적힌 구슬이 있다. 이 중 중복을 허락하여 m번을 뽑아 일렬로 나열하는 방법을 모두 출력하라.
10분
`순열`: 서로 다른 n개가 있을 때, 중복을 허용하지 않고 r개를 나열하는 수 (nPr)
`중복순열`: 서로 다른 n개가 있을 때, 중복을 허용하고 r개를 나열하는 수 (nΠr)
||||||||||
|------|---|---|------|---|---|------|---|---|
|D(0)|||D(0)|||D(0)|||
|1|||2|||3|||
|temp = [1, _]|||temp = [2, _]|||temp = [3, _]
|D(1)|||D(1)|||D(1)|||
|1|2|3|1|2|3|1|2|3|
|temp = [1, 1]|temp = [1, 2]|temp = [1, 3]|temp = [2, 1]|temp = [2, 2]|temp = [2, 3]|temp = [3, 1]|temp = [3, 2]|temp = [3, 3]|
|D(2)|D(2)|D(2)|D(2)|D(2)|D(2)|D(2)|D(2)|D(2)|
> [23-02-11] 중복순열연습 (0단계)

- jeongs/feb/23-02-12-음양더하기.js
> [23-02-12] 음양더하기 [1단계]

- soba/feb/게임369.java
20분
1. int형을 String형으로 바꾸는 방법 String.valueOf()
2. int형의 자릿수를 구하는 방법 (int)Math.log10() + 1 를 해주면 자릿수를 구할 수 있음.
> [2023-02-12]이것은 게임 369 문제입니디

- jeongs/feb/23-02-13-동전교환.js
다음과 같이 여러 단위의 동전들이 주어져 있을 때, 거스름돈을 가장 적은 수의 동전으로 교환해주려면 어떻게 주면 되는가? 각 단위의 동전은 무한정 쓸 수 있다.
답: 3, `[5, 5, 5]`가 가장 적은 동전의 경우의 수 
20분
필요없는 가지가 넓어지지 않게 쳐내는 로직을 추가하면 엄청나게 효율적이다.
> [23-02-13] 동전교환

- ezz/feb/2023-02-09-옷가게할인받기.java
문제 설명
머쓱이네 옷가게는 10만 원 이상 사면 5%, 30만 원 이상 사면 10%, 50만 원 이상 사면 20%를 할인해줍니다.
구매한 옷의 가격 price가 주어질 때, 지불해야 할 금액을 return 하도록 solution 함수를 완성해보세요.
제한사항
10 ≤ price ≤ 1,000,000
price는 10원 단위로(1의 자리가 0) 주어집니다.
소수점 이하를 버린 정수를 return합니다.
1시간 이상
삼항연산자로 돌려보고싶은데 실패함 다시 도전할거임 
[
](https://school.programmers.co.kr/learn/courses/30/lessons/120818)
> discount-money

- ezz/feb/2023-02-11-문자반복출력하기.java
문자열 my_string과 정수 n이 매개변수로 주어질 때, my_string에 들어있는 각 문자를 n만큼 반복한 문자열을 return 하도록 solution 함수를 완성해보세요.
제한사항
2 ≤ my_string 길이 ≤ 5
2 ≤ n ≤ 10
"my_string"은 영어 대소문자로 이루어져 있습니다.
20분 이내
자바 배열 정리 한 번 해야 할 듯  
https://school.programmers.co.kr/learn/courses/30/lessons/120825
> 문자 반복 출력하기

- ezz/feb/2023-02-12-특정문자제거하기.java
문제 설명
문자열 my_string과 문자 letter이 매개변수로 주어집니다. my_string에서 letter를 제거한 문자열을 return하도록 solution 함수를 완성해주세요.
제한 사항
1 ≤ my_string의 길이 ≤ 100
letter은 길이가 1인 영문자입니다.
my_string과 letter은 알파벳 대소문자로 이루어져 있습니다.
대문자와 소문자를 구분합니다.
15분 이내 (찾아봄)
String.replace() - (루프 내의 문자열에서 각 문자의 모든 발생을 제거하는 메서드)
https://school.programmers.co.kr/learn/courses/30/lessons/120826
https://kookyungmin.github.io/language/2018/05/22/java_06/
> 특정 문자 제거하기

- soba/feb/2023-02-13-피자나눠먹기2.java
> [2023-02-13]이것은 피자나눠먹기2 문제입니디

- jeongs/feb/23-02-14-순열구하기.js
10이하의 N개의 자연수가 주어지면 이 중 M개를 뽑아 일렬로 나열하는 방법을 모두 출력합니다.
20분
순열은 순서가 중요하기 때문에 중복이 있으면 안됨.
check 배열을 만들어 반복문 index에 해당하는 요소를 썼는지 안썼는지로 구분해줘야 함.
> [23-02-14] 순열구하기

- ezz/feb/2023-02-13-외계행성의나이.java
우주여행을 하던 머쓱이는 엔진 고장으로 PROGRAMMERS-962 행성에 불시착하게 됐습니다. 입국심사에서 나이를 말해야 하는데, PROGRAMMERS-962 행성에서는 나이를 알파벳으로 말하고 있습니다. a는 0, b는 1, c는 2, ..., j는 9입니다. 예를 들어 23살은 cd, 51살은 fb로 표현합니다. 나이 age가 매개변수로 주어질 때 PROGRAMMER-962식 나이를 return하도록 solution 함수를 완성해주세요.
제한 사항
age는 자연수입니다.
age ≤ 1,000
PROGRAMMERS-962 행성은 알파벳 소문자만 사용합니다.
입출력 예 설명
age가 23이므로 "cd"를 return합니다.
30분
https://school.programmers.co.kr/learn/courses/30/lessons/120834
https://developer-talk.tistory.com/411
> 구했다. 외계나이로

- jeongs/feb/23-02-15-팩토리얼.js
자연수 N을 입력하면 N!값을 구하세요. 
N! = n*(n-1)*(n-2)*.....*2*1입니다. 
만약 N=5라면 5!=5*4*3*2*1=120입니다.
15분
재귀는 거꾸로 거슬러 올라간다.
> [23-02-15] 팩토리얼

- soba/feb/2023-02-15-외계행성의나이.java
30분
만만히 봤다가 큰 코 다쳤다
아스키코드를 이용하는 건 익숙하지 않다 거의 첨 보는 듯?
0은 아스키코드로 48부터 시작
그리고 소문자 a는 아스키코드로 97부터 시작
대충 이정도는 알아두자
> [2023-02-15] 외계행성의 나이 문제입니다.

- ezz/feb/2023-02-14-진료순서정하기.java
외과의사 머쓱이는 응급실에 온 환자의 응급도를 기준으로 진료 순서를 정하려고 합니다. 정수 배열 emergency가 매개변수로 주어질 때 응급도가 높은 순서대로 진료 순서를 정한 배열을 return하도록 solution 함수를 완성해주세요.
30분 이상
https://school.programmers.co.kr/learn/courses/30/lessons/120835
https://coding-factory.tistory.com/548
https://velog.io/@happyeuni/Java-%EC%9E%90%EB%B0%94-%EB%B0%B0%EC%97%B4-%EB%B3%B5%EC%82%AC%ED%95%98%EA%B8%B0
> vip는 먼저 해드립니다.

- soba/feb/2023-02-16-문자열뒤집기.java
> [2023-02-16] 문자열 뒤집기 문제입니다.

- jeongs/feb/23-02-17-조합의경우수.js
nCr = n! / (nr - r)! * r!로 계산합니다. 이 공식을 쓰지않고 다음 공식을 사용하여 재귀를 이용해 조합수를 구해주는 프로그램을 작성하세요.
nCr = n-1Cr-1 + n-1Cr
30분
이차원배열로 된 배열에 리턴값을 저장해두고 메모이제이션을 하면, 재귀를 또 돌지않고 엄청나게 빠르게 계산할 수 있다.
> [23-02-17] 조합의 경우 수

- jeongs/feb/23-02-17-수열추측하기.js
가장 윗줄에 1부터 N까지의 숫자가 한 개씩 적혀 있다. 그리고 둘째 줄부터 차례대로 파스칼 의 삼각형처럼 위의 두개를 더한 값이 저장되게 된다. 
예를 들어 N이 4 이고 가장 윗 줄에 3 1 2 4 가 있다고 했을 때, 다음과 같은 삼각형이 그려진다.
```tsx
3 1 2 4 
4 3 6 
7 9 
16
```
N과 가장 밑에 있는 숫자가 주어져 있을 때 가장 윗줄에 있는 숫자를 구하는 프로그램을 작성하시오. 
단, 답이 여러가지가 나오는 경우에는 사전순으로 가장 앞에 오는 것을 출력하여야 한다.
첫째 줄에 두개의 정수 N(1≤N≤10)과 F가 주어진다. N은 가장 윗줄에 있는 숫자의 개수를 의 미하며 F는 가장 밑에 줄에 있는 수로 1,000,000 이하이다.
첫째 줄에 삼각형에서 가장 위에 들어갈 N개의 숫자를 빈 칸을 사이에 두고 출력한다. 답이 존재 하지 않는 경우는 입력으로 주어지지 않는다.
▣ 입력예제 1 4 16
▣ 출력예제 1 3124
40분
원래라면 순열로 각 배열을 구한다음 하위로 내려가며 다 더해서 16인 경우를 찾아야 하지만 엄청 복잡해짐.
조합을 이용해 꼼수를 쓸 수 있음.
우선 아래와 같이 반복되는 식을 찾아내야 함.
예를 들어 n = 6일 때, 파스칼의 삼각형처럼 식을 구해본다면 1 * 1 + 2 * 5 + 3 * 10 + 4 * 10 + 5 * 5 + 6 * 1 의 식을 찾을 수 있고,
이것은 조합으로 사진의 분홍색 영역과 같이 나옴. 
그럼 순열을 돌면서 각 자리수에서 조합으로 나온 값을 곱해주고, 그 총합이 F가 되면 그게 답이 되는 거임. (먼소린지 복잡하다)
여기서 …
> [23-02-17] 수열 추측하기

- soba/feb/2023-02-17-대문자와소문자.java
15분
대문자 알파벳과 소문자 알파벳은 아스키 코드로 32 만큼 차이가 난다는 것을 배웠다.
> [2023-02-17] 대문자와 소문자 문제입니다.

- jeongs/feb/23-02-18-완주하지못한선수.js
> [2023-02-18] 완주하지못한선수 [1단계]

- jeongs/feb/23-02-20-기능개발.js
<h6 class="guide-section-title" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; -webkit-font-smoothing: antialiased; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); …
> [23-02-20] 기능개발 [2단계]

- soba/feb/2023-02-19-n의배수고르기.java
30분
넘 어려웠어요..
N의 배수의 숫자 만큼 배열의 크기를 설정해주는 작업을 따로 하고
그 담에 (n % == 0) 을 이용해서 n의 배수를 추출해주는 작업을 했습니다..
> 2023 02 19 n의배수고르기 soba

- jeongs/feb/23-02-21-1차비밀지도.js
<h2 style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0.25rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 26px; line-height: 1.4; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; letter-spacing: -0.009em; -webkit-font-smoothing: antialiased; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); text-decoration-thickness: …
> [23-02-21] 1차 비밀지도

- ezz/feb/2023-02-24-머쓱이보다큰사람.java
머쓱이는 학교에서 키 순으로 줄을 설 때 몇 번째로 서야 하는지 궁금해졌습니다. 머쓱이네 반 친구들의 키가 담긴 정수 배열 array와 머쓱이의 키 height가 매개변수로 주어질 때, 머쓱이보다 키 큰 사람 수를 return 하도록 solution 함수를 완성해보세요.
제한 사항
1 ≤ array의 길이 ≤ 100
1 ≤ height ≤ 200
1 ≤ array의 원소 ≤ 200
5분미만
휘유 안하다가 하려니 힘들다!
https://school.programmers.co.kr/learn/courses/30/lessons/120585
> 머쓱이보다 큰 사람

- ezz/feb/2023-02-23-편지.java
- ezz/feb/2023-02-24-머쓱이보다큰사람.java
머쓱이는 할머니께 생신 축하 편지를 쓰려고 합니다. 할머니가 보시기 편하도록 글자 한 자 한 자를 가로 2cm 크기로 적으려고 하며, 편지를 가로로만 적을 때, 축하 문구 message를 적기 위해 필요한 편지지의 최소 가로길이를 return 하도록 solution 함수를 완성해주세요.
제한 사항
공백도 하나의 문자로 취급합니다.
1 ≤ message의 길이 ≤ 50
편지지의 여백은 생각하지 않습니다.
message는 영문 알파벳 대소문자, ‘!’, ‘~’ 또는 공백으로만 이루어져 있습니다.
5분 미만
쉬운 걸 하니 손이 간다
https://school.programmers.co.kr/learn/courses/30/lessons/120898
> Programmers conding test/letter length

- ezz/feb/2023-02-21-배열의유사도.java
- ezz/feb/2023-02-22-중복된숫자개수.java
- ezz/feb/2023-02-23-편지.java
- ezz/feb/2023-02-24-머쓱이보다큰사람.java
두 배열이 얼마나 유사한지 확인해보려고 합니다. 문자열 배열 s1과 s2가 주어질 때 같은 원소의 개수를 return하도록 solution 함수를 완성해주세요.
제한 사항
1 ≤ s1, s2의 길이 ≤ 100
1 ≤ s1, s2의 원소의 길이 ≤ 10
s1과 s2의 원소는 알파벳 소문자로만 이루어져 있습니다
s1과 s2는 각각 중복된 원소를 갖지 않습니다.
5분 미만
나의 시간은 거꾸로 간다
https://school.programmers.co.kr/learn/courses/30/lessons/120903
> Programmers conding test/array similarity

- hdp/feb/2023-02-26-x만큼간격이있는n개의숫자.java
10분 미만
변수 val을 int형으로 사용했었다가 오버플로가 발생했었다. 값의 범위를 잘 생각해야겠다.
https://school.programmers.co.kr/learn/courses/30/lessons/12954
> Programmers conding test/daepyo sample

- jeongs/feb/23-02-26-최소직사각형.js
> [23-02-26] 최소직사각형 [1단계]

- ezz/feb/2023-02-25-숨어있는숫자의덧셈1.java
문자열 my_string이 매개변수로 주어집니다. my_string안의 모든 자연수들의 합을 return하도록 solution 함수를 완성해주세요.
30분 미만
String 에서 contains로 비교하려고 했는데 중복된 숫자또한 체크하기 위해 char로 변경
https://school.programmers.co.kr/learn/courses/30/lessons/120851
> 숨어있는 숫자의 덧셈

- README.md
> Hdp picture

- jeongs/feb/23-02-27-이진변환반복하기.js
> [23-02-27] 이진변환반복하기 [2단계]

- jeongs/mar/23-03-01-k번째수.js
<h6 class="guide-section-title" style="box-sizing: border-box; padding: 0px; margin: 0px 0px 1rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-weight: 700; font-stretch: inherit; font-size: 14px; line-height: 1.5; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; -webkit-font-smoothing: antialiased; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(38, 55, 71); …
> [23-03-01] k번째수 [1단계]

- jeongs/mar/23-03-01-프린터.js
> [23-03-01] 프린터 [2단계]

- hdp/feb/2023-02-27-소수찾기.java
1부터 입력받은 숫자 n 사이에 있는 소수의 개수를 반환하는 함수, solution을 만들어 보세요.
소수는 1과 자기 자신으로만 나누어지는 수를 의미합니다.
(1은 소수가 아닙니다.)
1시간
처음에는 단순하게  소수 판별시 2부터 n-1까지 탐색하면서 나눠지면 소수가 아닌것으로 생각했는데 수가 커졌을 때 시간초과가 나서 찾아보니 2부터 제곱근까지만 탐색해도 됐다. 
이유는 제곱근 이후부터는 이전 체크와 중복되기 때문이다.(ex 16은 1*16, 2*8, 4*4(제곱근), 8*2, 16*1)
이 방법에서 더 나아간게 찾아보니 에라스토테네스의 체를 이용하는 방법인 것 같다. 
N 이하의 소수를 구하는 방법은
소수 판별 배열을 선언하고, 2부터 n의 제곱근까지 각 수의 배수들은 다 소수가 아님으로 판단해 나가면서 푸는 것 같다.
문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/12921
참고 링크 : https://st-lab.tistory.com/81
> 프로그래머스 1단계 소수찾기

- ezz/feb/2023-02-27-구슬을나누는경우의수.java
머쓱이는 구슬을 친구들에게 나누어주려고 합니다. 구슬은 모두 다르게 생겼습니다. 머쓱이가 갖고 있는 구슬의 개수 balls와 친구들에게 나누어 줄 구슬 개수 share이 매개변수로 주어질 때, balls개의 구슬 중 share개의 구슬을 고르는 가능한 모든 경우의 수를 return 하는 solution 함수를 완성해주세요.
제한사항
1 ≤ balls ≤ 30
1 ≤ share ≤ 30
구슬을 고르는 순서는 고려하지 않습니다.
share ≤ balls
2시간 이상 3시간 넘을수도?
팩토리얼값을 구하게 되면 int의 범위따위 한참을 넘어버리기때문에 오버플로우?가 발생한다. 그러므로 무한마냥 큰 값을 다뤄야한다면 큰형님을 이용하자. 
참고로 BigInteger는 String이라 평범한 사칙연산은 허용하지 않는다. 격에 맞는 사칙연산으로 대우해줄 것.
https://school.programmers.co.kr/learn/courses/30/lessons/120840
https://st-lab.tistory.com/93
https://coding-factory.tistory.com/604
> 콩 한쪽도 나눠 먹자.

- jeongs/mar/23-03-02-7의개수.js
> [23-03-02] 7의 개수 [0단계]

- jeongs/mar/23-03-04-바탕화면정리.js
> [23-03-04] 바탕화면정리 [1단계]

- jeongs/mar/23-03-04-종이자르기.js
> [23-03-04] 종이자르기 [0단계]

- jeongs/mar/23-03-05-문자열밀기.js
> [23-03-05] 문자열밀기 [0단계]

- hdp/feb/2023-03-02-모의고사.java
45분
List<Integer> list -> int[]로 바꾸려면 list.stream().mapToInt(i->i).toArray();
https://school.programmers.co.kr/learn/courses/30/lessons/42840
> 프로그래머스 1단계 모의고사

- jeongs/mar/23-03-06-내적.js
> [23-03-06] 내적 [1단계]

- hdp/feb/2023-03-05-콜라츠추측
콜라츠 추측
1937년 Collatz란 사람에 의해 제기된 이 추측은, 주어진 수가 1이 될 때까지 다음 작업을 반복하면, 모든 수를 1로 만들 수 있다는 추측입니다. 작업은 다음과 같습니다.
1-1. 입력된 수가 짝수라면 2로 나눕니다. 
1-2. 입력된 수가 홀수라면 3을 곱하고 1을 더합니다. 
2. 결과로 나온 수에 같은 작업을 1이 될 때까지 반복합니다. 
예를 들어, 주어진 수가 6이라면 6 → 3 → 10 → 5 → 16 → 8 → 4 → 2 → 1 이 되어 총 8번 만에 1이 됩니다. 위 작업을 몇 번이나 반복해야 하는지 반환하는 함수, solution을 완성해 주세요. 단, 주어진 수가 1인 경우에는 0을, 작업을 500번 반복할 때까지 1이 되지 않는다면 –1을 반환해 주세요.
10분
문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/12943
> 2023-03-05-콜라츠추측

- hdp/feb/2023-03-07-두정수사이의합.java
두 정수 a, b가 주어졌을 때 a와 b 사이에 속한 모든 정수의 합을 리턴하는 함수, solution을 완성하세요.
예를 들어 a = 3, b = 5인 경우, 3 + 4 + 5 = 12이므로 12를 리턴합니다.
20분미만
문제 링크 : https://school.programmers.co.kr/learn/courses/30/lessons/12912
> 프로그래머스 1단계  두 정수 사이의 합

- ezz/mar/2023-03-07-문자열정렬하기1.java
문자열 my_string이 매개변수로 주어질 때, my_string 안에 있는 숫자만 골라 오름차순 정렬한 리스트를 return 하도록 solution 함수를 작성해보세요.
제한사항
1 ≤ my_string의 길이 ≤ 100
my_string에는 숫자가 한 개 이상 포함되어 있습니다.
my_string은 영어 소문자 또는 0부터 9까지의 숫자로 이루어져 있습니다.
30분 이상
https://school.programmers.co.kr/learn/courses/30/lessons/120850
https://sajagogumi.tistory.com/entry/%EC%A0%95%EA%B7%9C%ED%91%9C%ED%98%84%EC%8B%9D-0-9-%EB%9C%BB
> [2023-03-07]  문자열 정렬하기(1)

- ezz/mar/2023-03-08-세균증식.java
어떤 세균은 1시간에 두배만큼 증식한다고 합니다. 처음 세균의 마리수 n과 경과한 시간 t가 매개변수로 주어질 때 t시간 후 세균의 수를 return하도록 solution 함수를 완성해주세요.
제한사항
1 ≤ n ≤ 10
1 ≤ t ≤ 15
10분 이내
https://school.programmers.co.kr/learn/courses/30/lessons/120910
> [2023-03-07]  세균증식

- ezz/mar/2023-03-08-문자열정렬하기.java
영어 대소문자로 이루어진 문자열 my_string이 매개변수로 주어질 때, my_string을 모두 소문자로 바꾸고 알파벳 순서대로 정렬한 문자열을 return 하도록 solution 함수를 완성해보세요.
제한사항
0 < my_string 길이 < 100
20분 이내 
https://school.programmers.co.kr/learn/courses/30/lessons/120911
> [2023-03-08] 문자열 정렬하기(2)

- jeongs/mar/23-03-07-시저암호.js
> [23-03-08] 시저암호 [1단계]

- ezz/mar/2023-03-09-주사위의개수.java
머쓱이는 직육면체 모양의 상자를 하나 가지고 있는데 이 상자에 정육면체 모양의 주사위를 최대한 많이 채우고 싶습니다. 상자의 가로, 세로, 높이가 저장되어있는 배열 box와 주사위 모서리의 길이 정수 n이 매개변수로 주어졌을 때, 상자에 들어갈 수 있는 주사위의 최대 개수를 return 하도록 solution 함수를 완성해주세요.
제한사항
box의 길이는 3입니다.
box[0] = 상자의 가로 길이
box[1] = 상자의 세로 길이
box[2] = 상자의 높이 길이
1 ≤ box의 원소 ≤ 100
1 ≤ n ≤ 50
n ≤ box의 원소
주사위는 상자와 평행하게 넣습니다.
10분 이내
https://school.programmers.co.kr/learn/courses/30/lessons/120845
> [2023-03-09] 주사위의 개수

- jeongs/mar/23-03-09-외계어사전.js
> [23-03-09] 외계어 사전 [0단계]

- jeongs/mar/23-03-09-최댓값과최솟값.js
> [23-03-09] 최댓값과 최솟값 [2단계 (?)]

- jeongs/mar/23-03-11-세균증식.js
> [23-03-10] 세균증식 [0단계]

- jeongs/mar/23-03-10-잘라서배열로저장하기.js
> [23-03-12] 잘라서 배열로 저장하기 [0단계]

- jeongs/mar/23-03-12-하샤드수.js
> [23-03-12] 하샤드수 [1단계]

- hdp/mar/2023-03-10-음양더하기.java
> 2023-03-10-음양더하기.java

- hdp/mar/2023-03-11-폰켓몬.java
10분
Set 컬렉션을 많이 사용 안해봐서 가물가물해서 검색해서 사용했다.
중복 제거를 알아서 해 주기 때문에 이 문제에 적절하다고 생각했다.
문제 : https://school.programmers.co.kr/learn/courses/30/lessons/1845
참고 : https://wakestand.tistory.com/111
> 2023-03-11-폰켓몬.java

- ezz/mar/2023-03-10-최댓값만들기2.java
정수 배열 numbers가 매개변수로 주어집니다. numbers의 원소 중 두 개를 곱해 만들 수 있는 최댓값을 return하도록 solution 함수를 완성해주세요.
제한사항
-10,000 ≤ numbers의 원소 ≤ 10,000
2 ≤ numbers 의 길이 ≤ 100
40분 이상
반복문을 내려놓고 좀 더 간단한 방법이 없을지 고민하자.
https://school.programmers.co.kr/learn/courses/30/lessons/120862
> [ 2023-03-10 ] 최댓값 만들기 (2)

- hdp/mar/2023-03-12-문자열나누기.java
> 2023-03-12-문자열나누기.java

- jeongs/mar/23-03-13-컨트롤제트.js
> [23-03-13] 컨트롤제트 [0단계]

- ezz/mar/2023-03-11-2차원으로만들기.java
정수 배열 num_list와 정수 n이 매개변수로 주어집니다. num_list를 다음 설명과 같이 2차원 배열로 바꿔 return하도록 solution 함수를 완성해주세요.
num_list가 [1, 2, 3, 4, 5, 6, 7, 8] 로 길이가 8이고 n이 2이므로 num_list를 2 * 4 배열로 다음과 같이 변경합니다. 2차원으로 바꿀 때에는 num_list의 원소들을 앞에서부터 n개씩 나눠 2차원 배열로 변경합니다.
제한사항
num_list의 길이는 n의 배 수개입니다.
0 ≤ num_list의 길이 ≤ 150
2 ≤ n < num_list의 길이
20분 이내
[
](https://school.programmers.co.kr/learn/courses/30/lessons/120842)
> [ 2023-03-11 ] 이차원으로 만들기 

- soba/mar/2023-03-12-A로B만들기.java
1시간 이상
어떤식으로 풀어야 하는 지 몰랐다.
String은 각각 고유의 char 번호가 있기 때문에,
문자열을 toCharArray()를 이용해 char형 배열로 변환해주고,
그걸 sort로 정렬하여 두 문자열을 비교하면 되는
아주 간단한 문제였다.
+)
1. String[] tmp1 = before.split(""); -> call by reference
2. char[] tmp1 = before.toCharArray(); ->  call by value
따라서 첫번째는
String str1 = String.valueOf(tmp1); 를 실행하면 리퍼런스값이 리턴되어 str1 값에 들어가고
두번째는
String str1 = String.valueOf(tmp1); 를 실행하면 리터럴이 리턴되어 str1 값에 들어간다
첫번째 방식으로 리턴하여 equals() 하게 되면 주소값끼리 비교되어 리티럴이 같아도 false가 발생한다
그래서 1번 같은 방식이 아닌 toCharArray() 를 이용하여 리터럴끼리 비교해주는 것.
별개로 Arrays.toSring은 배열안의 리터럴 값을 리턴해주는 메소드라 이걸 쓰면 1번 방법을 쓰든 2번 방법을 쓰든 상관없다.
결론)
1. 리터럴을 비교해주는 문제는 call by reference와 call by value를 잘 구분하고 활용할 줄 알아야 한다
2. String.valueOf()는 파라미터가 call by reference일때는 주소값 , 파라미터가 call by value 일때는 값을 출력해 준다. 즉 기본형들을 String형으로 변환할 때 쓰는 메소드다
3. …
> [2023-03-12] A로 B만들기 문제입니다

- hdp/mar/2023-03-13-제일작은수제거하기.java
> 2023-03-13-제일작은수제거하기.java

- jeongs/mar/23-03-14-제일작은수제거하기.js
> [23-03-14] 제일작은수제거하기 [1단계]

- jeongs/mar/23-03-14-같은숫자는싫어.js
> [23-03-14] 같은 숫자는 싫어 [1단계]

- ezz/mar/2023-03-15-인덱스바꾸기.java
문제 설명
문자열 my_string과 정수 num1, num2가 매개변수로 주어질 때, my_string에서 인덱스 num1과 인덱스 num2에 해당하는 문자를 바꾼 문자열을 return 하도록 solution 함수를 완성해보세요.
제한사항
1 < my_string의 길이 < 100
0 ≤ num1, num2 < my_string의 길이
my_string은 소문자로 이루어져 있습니다.
num1 ≠ num2
20분 이내
(https://school.programmers.co.kr/learn/courses/30/lessons/120895)
> [ 2023-03-15 ]인덱스 바꾸기

- soba/mar/2023-03-14-문자열안에문자열.java
5분
문자열안에 특정 문자열이 포함되어있는지 확인하는 메소드는 contains()
https://school.programmers.co.kr/learn/courses/30/lessons/120908
> [2023-03-14] 문자열안에 문자열 문제입니다.

- hdp/mar/2023-03-14-없는숫자더하기.java
> 2023-03-14-없는숫자더하기.java

- jeongs/mar/23-03-15-문자열내마음대로정렬하기.js
> [23-03-15] 문자열 내 마음대로 정렬하기 [1단계]

- ezz/mar/2023-03-14-공던지기.java
문제 설명
머쓱이는 친구들과 동그랗게 서서 공 던지기 게임을 하고 있습니다. 공은 1번부터 던지며 오른쪽으로 한 명을 건너뛰고 그다음 사람에게만 던질 수 있습니다. 친구들의 번호가 들어있는 정수 배열 numbers와 정수 K가 주어질 때, k번째로 공을 던지는 사람의 번호는 무엇인지 return 하도록 solution 함수를 완성해보세요.
제한사항
2 < numbers의 길이 < 100
0 < k < 1,000
numbers의 첫 번째와 마지막 번호는 실제로 바로 옆에 있습니다.
numbers는 1부터 시작하며 번호는 순서대로 올라갑니다.
1시간 이내
엄청 간단하게 풀 수 있던건데 반복문에 집작하는듯 반성하자
https://school.programmers.co.kr/learn/courses/30/lessons/120843
> [ 2023- 03- 14 ]공 던지기

- soba/mar/2023-03-15-평균구하기.java
5분
https://school.programmers.co.kr/learn/courses/30/lessons/12944
> [2023-03-15] 평균구하기 문제입니다.

- jeongs/mar/23-03-16-JadenCase문자열만들기.js
> [23-03-16] JadenCase 문자열 만들기 [2단계]

- hdp/mar/2023-03-15-가운데글자가져오기.java
> 2023-03-15-가운데글자가져오기.java

- hdp/mar/2023-03-16-수박수박수박수박수박수.java
> 2023-03-16-수박수박수박수박수박수.java

- ezz/mar/2023-03-17-합성수찾기.java
약수의 개수가 세 개 이상인 수를 합성수라고 합니다. 자연수 n이 매개변수로 주어질 때 n이하의 합성수의 개수를 return하도록 solution 함수를 완성해주세요.
제한사항
1 ≤ n ≤ 100
30분 이내
반복문안에 반목문을 넣고 원하는 값을 리턴하려고 짜맞추는게 헷갈렸다.
(https://school.programmers.co.kr/learn/courses/30/lessons/120846)
> [ 2023 - 03 - 17 ] 합성수 찾기

- jeongs/mar/23-03-17-올바른괄호.js
> [23-03-17] 올바른 괄호 [2단계]

- hdp/mar/2023-03-17-가장가까운같은글자.java
<html>
<body>
<ul class="challenge-nav nav nav-tabs nav-tabs-dark task-tab" id="tab" role="tablist" style="box-sizing: border-box; padding: 0px 1rem; margin: 0px; color: rgb(38, 55, 71); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; display: flex; flex-wrap: …
> 2023-03-17-가장가까운같은글자.java

- soba/mar/2023-03-17-음양더하기.java
5분
너무 쉬운데용;
https://school.programmers.co.kr/learn/courses/30/lessons/76501
> [2023-03-17] 음양더하기 문제입니다.

- ezz/mar/2023-03-18-팩토리얼.java
i팩토리얼 (i!)은 1부터 i까지 정수의 곱을 의미합니다. 예를들어 5! = 5 * 4 * 3 * 2 * 1 = 120 입니다. 정수 n이 주어질 때 다음 조건을 만족하는 가장 큰 정수 i를 return 하도록 solution 함수를 완성해주세요.
i! ≤ n
제한사항
0 < n ≤ 3,628,800
15분 이내 
유후
https://school.programmers.co.kr/learn/courses/30/lessons/120848
> [ 2023 - 03 - 18 ] 팩토리얼

- hdp/mar/2023-03-18-문자열다루기기본.java
> 2023-03-18-문자열다루기기본.java

- ezz/mar/2023-03-19-369게임.java
머쓱이는 친구들과 369게임을 하고 있습니다. 369게임은 1부터 숫자를 하나씩 대며 3, 6, 9가 들어가는 숫자는 숫자 대신 3, 6, 9의 개수만큼 박수를 치는 게임입니다. 머쓱이가 말해야하는 숫자 order가 매개변수로 주어질 때, 머쓱이가 쳐야할 박수 횟수를 return 하도록 solution 함수를 완성해보세요.
제한사항
1 ≤ order ≤ 1,000,000
15분 이내
이게 5점이라니!
https://school.programmers.co.kr/learn/courses/30/lessons/120891
> [ 2023 - 03 -19 ] 369게임

- hdp/mar/2023-03-19-부족한금액계산하기.java
<html>
<body>
<ul class="challenge-nav nav nav-tabs nav-tabs-dark task-tab" id="tab" role="tablist" style="box-sizing: border-box; padding: 0px 1rem; margin: 0px; color: rgb(38, 55, 71); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: inherit; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; display: flex; flex-wrap: …
> 2023-03-19-부족한금액계산하기.java

- jeongs/mar/23-03-20-캐릭터의좌표.js
> [23-03-20] 캐릭터의 좌표 [1단계]

- soba/mar/2023-03-20-k의개수.java
15분
int 에다 "" 를 붙이면 string형이 된다
https://school.programmers.co.kr/learn/courses/30/lessons/120887
> [2023-03-20] k의 개수 문제입니다.

- soba/mar/2023-03-19-짝수와홀수.java
1분컷
졸립네요
https://school.programmers.co.kr/learn/courses/30/lessons/12937
> [2023-03-19] 짝수와 홀수 문제입니다.

- hdp/mar/2023-03-20-행렬의덧셈.java
> 2023-03-20-행렬의덧셈.java

- ezz/mar/2023-03-21-가장큰수찾기.java
> [ 2023 - 03 - 21 ] 가장 큰 수 찾기

- jeongs/mar/23-03-21-로그인성공.js
> [23-03-21] 로그인 성공 [0단계]

- jeongs/mar/23-03-22-영어가싫어요.js
> [23-03-22] 영어가싫어요 [0단계]

- soba/mar/2023-03-21-진료순서정하기.java
20분
집중을 빡 하고 곰곰히 생각하면 쉽게 풀린다
이중 for문 열심히 반복하자
https://school.programmers.co.kr/learn/courses/30/lessons/120835
> [2023-03-21] 진료순서 정하기 문제입니다.

- hdp/mar/2023-03-21-최대공약수와최소공배수.java
> 2023-03-21-최대공약수와최소공배수.java

- jeongs/mar/23-03-23-특이한정렬.js
> [23-03-23] 특이한 정렬 [0단계]

- soba/mar/2023-03-22-가까운수.java
40분
최솟값을 미리 설정해두고 조건에 따라 비교하며 최솟값을 교체해주는 방식을 통해 값을 구하자
마구잡이로 하지 말고 초반에 방향을 잘 잡자
https://school.programmers.co.kr/learn/courses/30/lessons/120890#
> [2023-03-22]  가까운 수 문제입니다.

- hdp/mar/2023-03-22-같은숫자는싫어!.java
> 2023-03-22-같은숫자는싫어!.java

- hdp/mar/2023-03-23-3진법뒤집기.java
> 2023-03-23-3진법뒤집기.java

- hdp/mar/2023-03-24-예산.java
> 2023-03-24-예산.java

- ezz/mar/2023-03-22-소인수분해.java
> [ 2023 - 03 - 22] 소인수분해

- ezz/mar/2023-03-24-숫자찾기.java
> [ 2023 - 03 -24 ] 숫자 찾기

- jeongs/mar/23-03-24-뉴스클러스트링.js
<p style="box-sizing: border-box; padding: 0px; margin: 0.75rem 0px 0px; color: rgb(178, 192, 204); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 400; font-stretch: inherit; font-size: 16px; line-height: 1.8; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; letter-spacing: -0.1px; overflow-wrap: break-word; orphans: 2; text-align: left; text-indent: 0px; text-transform: …
> [23-03-24] 뉴스클러스트링 [2단계]

- soba/mar/2023-03-23-없는숫자더하기.java
15분
이런식의 풀이도 가능하다 ;
https://school.programmers.co.kr/learn/courses/30/lessons/86051
> [2023-03-23] 없는 숫자 더하기 문제입니다.

- soba/mar/2023-03-24-칠의개수.java
> [2023-03-24] 7의 개수 문제입니다.

- soba/mar/2023-03-25-최댓값과최솟값.java
30분
생각하는데 시간이 꽤 걸렸다.
일단 최솟값과 최댓값을 구하는 문제이기에 정렬이 필요한데
그럴려면 문자열을 배열로 바꿔줘야 한다.
근데 여기서 음수가  -, 1 같은 형태로 구분되지 않아야 하며
숫자들 사이에 공백이 있다는 특징이 있음 -> 공백이 있다는것이 힌트 였다 규칙적인 패턴으로 분류되어있다는 뜻 -> split사용
(여기까지 생각하는데 시간이 꽤 걸림)
그 다음부터는 쉽게 쉽게 풀렸다
https://school.programmers.co.kr/learn/courses/30/lessons/12939
> [2023-03-25] 최댓값과 최솟값문제입니다

- jeongs/mar/23-03-27-2016년.js
> [23-03-27] 2016년 [1단계]

- ezz/mar/2023-03-27-중복된문자제거.java
> [ 2023 - 03 - 27 ] 중복된 문자 제거

- jeongs/mar/23-03-28-방금그곡.js
<h2 style="box-sizing: border-box; padding: 0px; margin: 0px 0px 0.25rem; color: white; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-variant-numeric: inherit; font-variant-east-asian: inherit; font-variant-alternates: inherit; font-weight: 700; font-stretch: inherit; font-size: 26px; line-height: 1.4; font-family: Inter, NotoSansKR, &quot;Helvetica Neue&quot;, Helvetica, Arial, &quot;맑은 고딕&quot;, &quot;malgun gothic&quot;, 돋움, Dotum, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Noto Color Emoji&quot;; font-optical-sizing: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; letter-spacing: -0.009em; -webkit-font-smoothing: antialiased; orphans: 2; text-align: left; text-indent: 0px; text-transform: …
> [2023-03-28] 방금그곡 [3단계]

- jeongs/mar/23-03-27-tuple.js
> [23-03-27] 튜플

- soba/mar/2023-03-26-수박수박수박수박수박수.java
3분
후후 이정도면 이제 금방 푼다
https://school.programmers.co.kr/learn/courses/30/lessons/12922
> [2023-03-26] 수박수박수박수박수박수 문제입니다.

- soba/mar/2023-03-27-컨트롤제트.java
10분~15분
훗
https://school.programmers.co.kr/learn/courses/30/lessons/120853
> [2023-03-27] 컨트롤 제트 문제입니다.

- soba/mar/2023-03-28-JadenCase문자열만들기.java
1시간 이상
나의 현재 지식으로는 굉장히 어려웠다.
다른 케이스들은 조건에 맞게 잘 설정했는데,
공백이 연속으로 있을 때의 케이스에서 대처를 하지 못하였다..
결국 풀이를 보았다..
일단 숫자도 따로 케이스를 구분해야 할 줄 알았는데 할 필요없이 숫자에 toUpperCase()를 적용해도 에러가 안난다.
공백도 마찬가지 그냥 공백과 숫자가 출력된다.
이것을 이용 처음에 toUpperCase()를 사용하고
그 후 공백이 나오지않으면 boolean형 변수에 false를 넣어 소문자만 출력되게하고,
공백이 나오면 boolean형 변수에 true를 넣어 대문자를 출력하게 한다.
그리고 삼항연산자로 푸는 것 보다 StringBuilder 사용하는게 속도가 훨씬 빠르다
삼항연산자로 풀었을 때
StringBuilder로 풀었을 때
https://school.programmers.co.kr/learn/courses/30/lessons/12951#
> [2023-03-28] JadenCase문자열만들기 입니다.

- ezz/mar/2023-03-28-A로B만들기.java
> [ 2023 - 03 - 28 ] A로 B 만들기

- jeongs/mar/23-03-29-숨어있는숫자의덧셈.js
> [2023-03-29] 숨어있는 숫자의 덧셈 [0단계]

- hdp/mar/2023-03-25-시저암호.java
> 2023-03-25-시저암호.java

- hdp/mar/2023-03-26-삼총사.java
> 2023-03-26-삼총사.java

- hdp/mar/2023-03-28-문자열내마음대로정렬하기.java
> 2023-03-28-문자열내마음대로정렬하기.java

- soba/mar/2023-03-29-문자열다루기기본.java
10분
크 try catch 이용하는 방법도 있다
https://school.programmers.co.kr/learn/courses/30/lessons/12918
> [2023-03-29] 문자열 다루기 기본 문제입니다.
